#!/bin/bash

echo "🚀 Todo App Deployment Script"
echo "=============================="
echo ""

echo "📱 Step 1: Frontend Deployment (Vercel)"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repository: Nithin0525/myToDo-Application"
echo "4. Configure settings:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "5. Add environment variable: REACT_APP_API_URL = https://your-backend-url.railway.app"
echo "6. Click 'Deploy'"
echo ""

echo "🔧 Step 2: Backend Deployment (Railway)"
echo "1. Go to https://railway.app"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose your repository: Nithin0525/myToDo-Application"
echo "5. Set Root Directory to: backend"
echo "6. Add environment variables:"
echo "   - PORT=5001"
echo "   - MONGO_URI=mongodb+srv://Nithin:nysv%402444@cluster0.ay94z6o.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0"
echo "   - JWT_SECRET=your_super_secret_jwt_key_here"
echo "   - NODE_ENV=production"
echo "7. Railway will auto-deploy"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "1. Get your Railway backend URL"
echo "2. Go to Vercel dashboard"
echo "3. Update REACT_APP_API_URL with your Railway URL"
echo "4. Redeploy frontend"
echo ""

echo "🧪 Step 4: Test Your Deployment"
echo "1. Test backend: curl https://your-backend-url.railway.app/api/health"
echo "2. Test frontend: Visit your Vercel URL"
echo "3. Register and test all features"
echo ""

echo "✅ Deployment Complete!"
echo "Your todo-app will be live and accessible from anywhere!"
echo ""
echo "Frontend URL: https://your-app-name.vercel.app"
echo "Backend URL: https://your-backend-name.railway.app"
echo "Database: MongoDB Atlas (already configured)" 