#!/bin/bash

echo "🚀 Vercel Deployment Script"
echo "==========================="
echo ""

echo "📋 Prerequisites:"
echo "1. Vercel account: https://vercel.com/signup"
echo "2. GitHub repository ready"
echo "3. MongoDB Atlas configured"
echo ""

echo "🚀 Step 1: Deploy Backend to Vercel"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import repository: Nithin0525/myToDo-Application"
echo "4. Configure settings:"
echo "   - Framework Preset: Node.js"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Output Directory: backend"
echo "5. Add environment variables:"
echo "   MONGO_URI = mongodb+srv://Nithin:nysv%402444@cluster0.ay94z6o.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0"
echo "   JWT_SECRET = your_super_secret_jwt_key_here"
echo "   NODE_ENV = production"
echo "6. Deploy and note your backend URL"
echo ""

echo "📱 Step 2: Deploy Frontend to Vercel"
echo "1. Go back to Vercel Dashboard"
echo "2. Click 'New Project'"
echo "3. Import same repository: Nithin0525/myToDo-Application"
echo "4. Configure settings:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "5. Add environment variable:"
echo "   REACT_APP_API_URL = https://your-backend-name.vercel.app"
echo "6. Deploy"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "1. Get your backend URL from Step 1"
echo "2. Update frontend environment variable"
echo "3. Redeploy frontend"
echo ""

echo "🧪 Step 4: Test Your Deployment"
echo "1. Test backend: curl https://your-backend-name.vercel.app/api/health"
echo "2. Test frontend: Visit your frontend URL"
echo "3. Register and test all features"
echo ""

echo "✅ Deployment Complete!"
echo "Backend: https://your-backend-name.vercel.app"
echo "Frontend: https://your-frontend-name.vercel.app"
echo "Database: MongoDB Atlas (already configured)" 