#!/bin/bash

echo "🚀 Netlify Deployment Script"
echo "============================"
echo ""

echo "📋 Prerequisites:"
echo "1. Netlify account: https://app.netlify.com/signup"
echo "2. GitHub repository ready"
echo "3. Backend already deployed on Render"
echo ""

echo "🚀 Step 1: Deploy Frontend to Netlify"
echo "1. Go to https://app.netlify.com/"
echo "2. Click 'Add new site'"
echo "3. Select 'Import an existing project'"
echo "4. Connect to GitHub"
echo "5. Select repository: Nithin0525/myToDo-Application"
echo "6. Configure build settings:"
echo "   - Base directory: frontend"
echo "   - Build command: npm run build"
echo "   - Publish directory: build"
echo "7. Add environment variable:"
echo "   REACT_APP_API_URL = https://mytodo-application.onrender.com"
echo "8. Deploy site"
echo ""

echo "🔗 Step 2: Connect Frontend to Backend"
echo "1. Verify environment variable is set correctly"
echo "2. Test the connection"
echo "3. Register and test all features"
echo ""

echo "🧪 Step 3: Test Your Deployment"
echo "1. Test backend: curl https://mytodo-application.onrender.com/api/health"
echo "2. Test frontend: Visit your Netlify URL"
echo "3. Register and test all features"
echo ""

echo "✅ Deployment Complete!"
echo "Backend: https://mytodo-application.onrender.com"
echo "Frontend: https://your-site-name.netlify.app"
echo "Database: MongoDB Atlas (already configured)"
echo ""
echo "💡 Note: Netlify is excellent for React frontends!"
echo "Great choice for static site hosting with CDN" 