#!/bin/bash

echo "🚀 Heroku Deployment Script"
echo "==========================="
echo ""

echo "📋 Prerequisites:"
echo "1. Heroku account: https://signup.heroku.com/"
echo "2. Heroku CLI installed"
echo "3. Git repository ready"
echo ""

echo "🔧 Step 1: Install Heroku CLI"
echo "Download from: https://devcenter.heroku.com/articles/heroku-cli"
echo "Or run: npm install -g heroku"
echo ""

echo "🚀 Step 2: Deploy Backend to Heroku"
echo "1. Login to Heroku: heroku login"
echo "2. Create app: heroku create your-todo-app-backend"
echo "3. Set environment variables:"
echo "   heroku config:set MONGO_URI=\"mongodb+srv://Nithin:nysv%402444@cluster0.ay94z6o.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0\""
echo "   heroku config:set JWT_SECRET=\"your_super_secret_jwt_key_here\""
echo "   heroku config:set NODE_ENV=\"production\""
echo "4. Deploy: git push heroku main"
echo "5. Open app: heroku open"
echo ""

echo "📱 Step 3: Deploy Frontend to Vercel"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Import repository: Nithin0525/myToDo-Application"
echo "3. Configure:"
echo "   - Framework: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: build"
echo "4. Add env var: REACT_APP_API_URL = https://your-todo-app-backend.herokuapp.com"
echo "5. Deploy"
echo ""

echo "🔗 Step 4: Connect Frontend to Backend"
echo "1. Get Heroku URL: https://your-todo-app-backend.herokuapp.com"
echo "2. Update Vercel environment variable"
echo "3. Redeploy frontend"
echo ""

echo "🧪 Step 5: Test Deployment"
echo "1. Test backend: curl https://your-todo-app-backend.herokuapp.com/api/health"
echo "2. Test frontend: Visit your Vercel URL"
echo "3. Register and test all features"
echo ""

echo "✅ Deployment Complete!"
echo "Backend: https://your-todo-app-backend.herokuapp.com"
echo "Frontend: https://your-app-name.vercel.app"
echo "Database: MongoDB Atlas (already configured)" 