#!/bin/bash

echo "🚀 Render Deployment Script"
echo "=========================="
echo ""

echo "📋 Prerequisites:"
echo "1. Render account: https://render.com/"
echo "2. GitHub repository ready"
echo "3. MongoDB Atlas configured"
echo ""

echo "🚀 Step 1: Deploy Backend to Render"
echo "1. Go to https://dashboard.render.com/"
echo "2. Click 'New +'"
echo "3. Select 'Web Service'"
echo "4. Connect repository: Nithin0525/myToDo-Application"
echo "5. Configure settings:"
echo "   - Name: todo-app-backend"
echo "   - Environment: Node"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: node server.js"
echo "6. Add environment variables:"
echo "   NODE_ENV = production"
echo "   PORT = 5001"
echo "   MONGO_URI = mongodb+srv://Nithin:nysv%402444@cluster0.ay94z6o.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0"
echo "   JWT_SECRET = your_super_secret_jwt_key_here"
echo "7. Deploy and note your backend URL"
echo ""

echo "📱 Step 2: Deploy Frontend to Render"
echo "1. Go back to Render Dashboard"
echo "2. Click 'New +'"
echo "3. Select 'Static Site'"
echo "4. Connect same repository: Nithin0525/myToDo-Application"
echo "5. Configure settings:"
echo "   - Name: todo-app-frontend"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: build"
echo "6. Add environment variable:"
echo "   REACT_APP_API_URL = https://your-backend-name.onrender.com"
echo "7. Deploy"
echo ""

echo "🔗 Step 3: Connect Frontend to Backend"
echo "1. Get your backend URL from Step 1"
echo "2. Update frontend environment variable"
echo "3. Redeploy frontend"
echo ""

echo "🧪 Step 4: Test Your Deployment"
echo "1. Test backend: curl https://your-backend-name.onrender.com/api/health"
echo "2. Test frontend: Visit your frontend URL"
echo "3. Register and test all features"
echo ""

echo "✅ Deployment Complete!"
echo "Backend: https://your-backend-name.onrender.com"
echo "Frontend: https://your-frontend-name.onrender.com"
echo "Database: MongoDB Atlas (already configured)"
echo ""
echo "💡 Note: Render free tier may have some limitations"
echo "Services may sleep after inactivity on free tier" 