services:
  - type: web
    name: todo-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://Nithin:nysv%402444@cluster0.ay94z6o.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here 